CREATE TABLE ID (
  id INT PRIMARY KEY NOT NULL UNIQUE,
  fname VARCHAR(20),
  lname VARCHAR(20),
  phone VARCHAR(14),
  location VARCHAR(150),
  password VARCHAR(128),
  salt VARCHAR(70)
);


CREATE TABLE Month (
  mid int PRIMARY KEY,
  month VARCHAR(10)
);

CREATE TABLE Interaction (
  Interaction_id INT PRIMARY KEY,
  month_id INT REFERENCES Month(mid),
  day_of_month INT,
  id1 INT,
  id2 INT,
  FOREIGN KEY (id1) REFERENCES ID(id),
  FOREIGN KEY (id2) REFERENCES ID(id)
);


INSERT INTO MONTH VALUES(1, "Jan");
INSERT INTO MONTH VALUES(2, "Feb");
INSERT INTO MONTH VALUES(3, "MAR");
INSERT INTO MONTH VALUES(4, "APR");
INSERT INTO MONTH VALUES(5, "MAY");
INSERT INTO MONTH VALUES(6, "JUN");
INSERT INTO MONTH VALUES(7, "JUL");
INSERT INTO MONTH VALUES(8, "AUG");
INSERT INTO MONTH VALUES(9, "SEP");
INSERT INTO MONTH VALUES(10, "OCT");
INSERT INTO MONTH VALUES(11, "NOV");
INSERT INTO MONTH VALUES(12, "DEC");

SELECT i.id2 AS otherID, COUNT(*) over() AS cnt
FROM Interaction as i
WHERE i.id1 == ?

Select id.salt AS salt, id.password AS pass
FROM ID AS id
Where id.id = ?

INSERT INTO ID VALUES (?, ?, ?, ?, ?, ?, ?)
INSERT INTO ID VALUES (0, "Kelvin", "Kam", 206973, "Seattle WA")
INSERT INTO ID VALUES (1, "Chris", "Yee", 123456, "BOSTON WA")
INSERT INTO INTERACTION VALUES (0, 1, 30, 0, 1)
INSERT INTO INTERACTION VALUES (?, ?, ?, ?, ?)
DELETE FROM INTERACTION; DELETE FROM ID;
