CREATE TABLE UserID (
  id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  fname VARCHAR(20) NOT NULL,
  lname VARCHAR(20) NOT NULL,
  phone VARCHAR(14)NOT NULL,
  email VARCHAR(100) NOT NULL,
  location VARCHAR(150),
  password VARCHAR(128) NOT NULL,
  salt VARCHAR(70) NOT NULL
);



CREATE TABLE Interaction (
  Interaction_id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  inter_date DATE NOT NULL,
  id1 INT NOT NULL,
  id2 INT NOT NULL,
  FOREIGN KEY (id1) REFERENCES UserID(id),
  FOREIGN KEY (id2) REFERENCES UserID(id)
);

SELECT i.id2 AS otherID
FROM Interaction as i
WHERE i.id1 == ?

INSERT INTO MONTH VALUES(1, "Jan");
INSERT INTO MONTH VALUES(2, "Feb");
INSERT INTO MONTH VALUES(3, "MAR");
INSERT INTO MONTH VALUES(4, "APR");
INSERT INTO MONTH VALUES(5, "MAY");
INSERT INTO MONTH VALUES(6, "JUN");
INSERT INTO MONTH VALUES(7, "JUL");
INSERT INTO MONTH VALUES(8, "AUG");
INSERT INTO MONTH VALUES(9, "SEP");
INSERT INTO MONTH VALUES(10, "OCT");
INSERT INTO MONTH VALUES(11, "NOV");
INSERT INTO MONTH VALUES(12, "DEC");

SELECT i.id2 AS otherID, COUNT(*) over() AS cnt
FROM Interaction as i
WHERE i.id1 == ?

Select id.salt AS salt, id.password AS pass
FROM ID AS id
Where id.id = ?

INSERT INTO UserID VALUES (?, ?, ?, ?, ?, ?, ?)
INSERT INTO UserID VALUES (0, "Kelvin", "Kam", 206973, "Seattle WA")
INSERT INTO UserID VALUES (1, "Chris", "Yee", 123456, "BOSTON WA")
INSERT INTO INTERACTION VALUES (0, 1, 30, 0, 1)
INSERT INTO INTERACTION VALUES (?, ?, ?, ?, ?)
DELETE FROM INTERACTION; DELETE FROM ID;
