//// <auto-generated />
//using AzureAPI.Model;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

//namespace AzureAPI.Migrations
//{
//    [DbContext(typeof(MedidContext))]
//    partial class MedidContextModelSnapshot : ModelSnapshot
//    {
//        protected override void BuildModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "3.1.6")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128)
//                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//            modelBuilder.Entity("AzureAPI.Model.UserId", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnName("id")
//                        .HasColumnType("int")
//                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//                    b.Property<string>("Email")
//                        .IsRequired()
//                        .HasColumnName("email")
//                        .HasColumnType("nvarchar(100)")
//                        .HasMaxLength(100);

//                    b.Property<string>("Fname")
//                        .IsRequired()
//                        .HasColumnName("fname")
//                        .HasColumnType("nvarchar(20)")
//                        .HasMaxLength(20);

//                    b.Property<string>("Lname")
//                        .IsRequired()
//                        .HasColumnName("lname")
//                        .HasColumnType("nvarchar(20)")
//                        .HasMaxLength(20);

//                    b.Property<string>("Location")
//                        .HasColumnName("location")
//                        .HasColumnType("nvarchar(150)")
//                        .HasMaxLength(150);

//                    b.Property<string>("Password")
//                        .IsRequired()
//                        .HasColumnName("password")
//                        .HasColumnType("nvarchar(128)")
//                        .HasMaxLength(128);

//                    b.Property<string>("Phone")
//                        .IsRequired()
//                        .HasColumnName("phone")
//                        .HasColumnType("nvarchar(14)")
//                        .HasMaxLength(14);

//                    b.Property<string>("Salt")
//                        .IsRequired()
//                        .HasColumnName("salt")
//                        .HasColumnType("nvarchar(70)")
//                        .HasMaxLength(70);

//                    b.HasKey("Id");

//                    b.ToTable("UserID");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
